[project]
name = "my-first-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain[anthropic]>=0.3.25",
    "langgraph>=0.4.7",
    "langgraph-cli[inmem]>=0.2.10",
    "python-dotenv>=1.1.0",
]
