[project]
name = "svelte-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "authlib>=1.4.0",
    "langchain[openai]==1.0.*",
    "langgraph==1.0.*",
    "langgraph-cli[inmem]==0.4.*",
    "langgraph-api==0.5.3",
    "python-dotenv>=1.1.0",
    "requests>=2.32.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.403",
    "ruff>=0.12.5",
]

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"
